### ISSUE TITLE
Landscape Ecology project code

### ISSUE THREAD

**Issue by jclbrooks** [jclbrooks/MD_Stream_Salamanders#3]
2d8f7730e84dcc7d14f13db2782cfcb92653e3a7
I'm having trouble with line 102... the resp.var parameter needs to be a vector but it won't convert

Let me know what you think..
@djhocking

**Comment by jclbrooks** [comment]
I also gave you several of the CSVs associated with the code, but you should just need the two RData files that are also in that folder

Let me know if you need anything else

**Comment by djhocking** [comment]
Just for completeness the more appropriate way would be to do

```
class(DFUSvec) <- "numeric"
```
