### ISSUE TITLE
Juvenile and adult rows need to be combined in Capitals dataset

### ISSUE THREAD

**Issue by jclbrooks** [jclbrooks/MD_Stream_Salamanders#5]
When I changed the age value of "juvenile" to "adult" in the Capitals dataset, it then made it seem like there were two rows or observations of adults at the same transect-date-species. The juvenile and adult rows need to be combined with summarize() ?? so that the left_join will work

Line 129 of "Landscape_MSOM.R" file

**Comment by djhocking** [comment]
Fixed with

```
  group_by(region, transect, date, visit, species, age) %>%
  summarise_all(.funs = sum) %>%
  ungroup() %>%
```
